/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package system.gui;

import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author User
 */
public class interfaceComentario extends javax.swing.JPanel {

  private String nome;
  private String comentario;

  public interfaceComentario(String nome, String comentario) {
    this.nome = nome;
    this.comentario = comentario;
    timer = new Timer();
    initComponents();
    jScrollPane1.setOpaque(false);
    jScrollPane1.getViewport().setOpaque(false);
    jScrollPane1.setBorder(null);
    jScrollPane1.setViewportBorder(null);
    Animate(comentario);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtComentario = new javax.swing.JTextArea();
    txtUser = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();

    setOpaque(false);

    jPanel1.setOpaque(false);
    jPanel1.setPreferredSize(new java.awt.Dimension(300, 100));

    jScrollPane1.setBorder(null);
    jScrollPane1.setFocusable(false);
    jScrollPane1.setOpaque(false);

    txtComentario.setEditable(false);
    txtComentario.setBackground(new java.awt.Color(27, 53, 97));
    txtComentario.setColumns(20);
    txtComentario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
    txtComentario.setForeground(new java.awt.Color(255, 255, 255));
    txtComentario.setLineWrap(true);
    txtComentario.setRows(5);
    txtComentario.setBorder(null);
    txtComentario.setFocusable(false);
    txtComentario.setText("");
    txtComentario.setOpaque(false);
    jScrollPane1.setViewportView(txtComentario);

    txtUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    txtUser.setForeground(new java.awt.Color(105, 182, 248));
    txtUser.setText(nome);
    txtUser.setFocusable(false);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtUser)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap()));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    jLabel1.setIcon(new javax.swing.ImageIcon("arquivo/imagem/comentt.png")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1));
  }// </editor-fold>

  public void Animate(String text) {
    timer.scheduleAtFixedRate(new TimerTask() {
      @Override
      public void run() {
        if (txtComentario.getText().equals(text)) {
          timer.cancel();
        }
        String nextChar = Character.toString(text.charAt(txtComentario.getText().length()));
        txtComentario.append(nextChar);
        jPanel1.validate();
        jPanel1.repaint();
      }
    }, 500, 100);
  }

  // Variables declaration - do not modify
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea txtComentario;
  private javax.swing.JLabel txtUser;
  private Timer timer;
  // End of variables declaration
}
