/*
 * Click nbfs://nbhost/systemFilesystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/systemFilesystem/Templates/GUIForms/JFrame.java to edit this template
 */
package system.gui;

import system.usuario.UsuarioAbstract;
import system.usuario.UsuarioPadrao;
import system.usuario.RepositorioUsuario;
import system.usuario.exceptions.VNException;
import system.usuario.exceptions.UEException;
import system.jogos.Jogo;

import java.util.Vector;
import javax.swing.JOptionPane;

public class Perfil extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Perfil(UsuarioAbstract usuario) {
        jogos = new Vector<String>();
        for(Jogo jogo : ((UsuarioPadrao) usuario).getJogos()){
          jogos.add(jogo.getNome());
        }
        repo = new RepositorioUsuario();
        this.usuario = usuario;
        initComponents();

        // Torna a JList transparente
        listaJogos.setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        userInfoPanel = new javax.swing.JPanel();
        nomeUser = new javax.swing.JLabel();
        creditosUser = new javax.swing.JLabel();
        btnMudarNome = new javax.swing.JButton();
        btnMudarSenha = new javax.swing.JButton();
        btnComprarCreditos = new javax.swing.JButton();
        meusjogosPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaJogos = new javax.swing.JList<>();
        backgroundPerfil = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SpaceArcadia");
        setResizable(false);

        userInfoPanel.setOpaque(false);

        nomeUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeUser.setText(usuario.getNome());
        nomeUser.setToolTipText("");
        nomeUser.setForeground(new java.awt.Color(255, 229, 0, 255));

        creditosUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditosUser.setText("Créditos: " + Double.toString(usuario.getCreditos()) + "C");
        creditosUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        creditosUser.setForeground(new java.awt.Color(255, 229, 0, 255));

        btnMudarNome.setText("Mudar Nome");
        btnMudarNome.setBorderPainted(false);
        btnMudarNome.setContentAreaFilled(false);
        btnMudarNome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMudarNome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMudarNome.setPreferredSize(new java.awt.Dimension(133, 23));
        btnMudarNome.setForeground(new java.awt.Color(255, 255, 255, 255));
        btnMudarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMudarNomeActionPerformed(evt);
            }
        });

        btnMudarSenha.setText("Mudar Senha");
        btnMudarSenha.setBorderPainted(false);
        btnMudarSenha.setContentAreaFilled(false);
        btnMudarSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMudarSenha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMudarSenha.setPreferredSize(new java.awt.Dimension(133, 23));
        btnMudarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMudarSenhaActionPerformed(evt);
            }
        });
        btnMudarSenha.setForeground(new java.awt.Color(255, 255, 255, 255));

        btnComprarCreditos.setText("Comprar Créditos");
        btnComprarCreditos.setBorderPainted(false);
        btnComprarCreditos.setContentAreaFilled(false);
        btnComprarCreditos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComprarCreditos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComprarCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarCreditosActionPerformed(evt);
            }
        });
        btnComprarCreditos.setForeground(new java.awt.Color(255, 255, 255, 255));

        javax.swing.GroupLayout userInfoPanelLayout = new javax.swing.GroupLayout(userInfoPanel);
        userInfoPanel.setLayout(userInfoPanelLayout);
        userInfoPanelLayout.setHorizontalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(nomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(creditosUser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnMudarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnMudarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnComprarCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        userInfoPanelLayout.setVerticalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(nomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(creditosUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnMudarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnMudarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnComprarCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        meusjogosPanel.setOpaque(false);

        listaJogos.setBackground(new java.awt.Color(0,0,0,1));
        listaJogos.setForeground(new java.awt.Color(255, 255, 255, 255));
        listaJogos.setModel(new javax.swing.AbstractListModel<String>() {
              Vector<String> strings = new Vector<String>(jogos);
              public int getSize() { return strings.size(); }
              public String getElementAt(int i) { return strings.get(i); }
          });
        listaJogos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listaJogos.setOpaque(false);
        jScrollPane1.setViewportView(listaJogos);

        javax.swing.GroupLayout meusjogosPanelLayout = new javax.swing.GroupLayout(meusjogosPanel);
        meusjogosPanel.setLayout(meusjogosPanelLayout);
        meusjogosPanelLayout.setHorizontalGroup(
            meusjogosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meusjogosPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        meusjogosPanelLayout.setVerticalGroup(
            meusjogosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(meusjogosPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        backgroundPerfil.setIcon(new javax.swing.ImageIcon("arquivo/imagem/Perfil.png")); // NOI18N

        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(userInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(meusjogosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPerfil)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(userInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(meusjogosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(backgroundPerfil)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>  

    private void btnMudarNomeActionPerformed(java.awt.event.ActionEvent evt) {
      String inputValue = JOptionPane.showInputDialog(this, "Qual será seu novo nome?");
      if(inputValue != null){
        try{
            repo.mudarNome(usuario.getNome(), inputValue);
            usuario = repo.procurar(inputValue);
            nomeUser.setText(usuario.getNome());
            JOptionPane.showMessageDialog(this, "Nome trocado com sucesso!");
          } catch(UEException e){
            JOptionPane.showMessageDialog(this, "Nome já existente!");
          } catch(Exception e) {
        	  e.printStackTrace();
          }
      } else{
        JOptionPane.showMessageDialog(this, "Nome não alterado!");
      }   
    }

    private void btnComprarCreditosActionPerformed(java.awt.event.ActionEvent evt) {                                                   
      String inputValue = JOptionPane.showInputDialog(this, "Quantos créditos quer comprar?");
      if(inputValue != null){
        try{
          double valor = Double.parseDouble(inputValue);
          repo.creditar(usuario.getNome(), valor);
          usuario = repo.procurar(usuario.getNome());
          creditosUser.setText(("Créditos: " + Double.toString(usuario.getCreditos()) + "C"));
          JOptionPane.showMessageDialog(this, "Créditos comprados com sucesso!");
        } catch(VNException e){
          JOptionPane.showMessageDialog(this, "O valor não pode ser negativo");
        } catch(NumberFormatException e){
          JOptionPane.showMessageDialog(this, "O valor deve ser um número");
        }
      } else{
        JOptionPane.showMessageDialog(this, "Créditos não comprados!");
      }
    }                                                  

    private void btnMudarSenhaActionPerformed(java.awt.event.ActionEvent evt) {                                              
        String inputValue = JOptionPane.showInputDialog(this, "Qual será sua nova senha?");
          if(inputValue != null && inputValue.length() > 0){
            repo.mudarSenha(usuario.getNome(), inputValue);
            usuario = repo.procurar(usuario.getNome());
            JOptionPane.showMessageDialog(this, "Senha trocada com sucesso!");
          } else{
            JOptionPane.showMessageDialog(this, "Insira uma senha!");
          }      
    }    

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {                                              
        new Catalogo(usuario).setVisible(true);
        this.dispose();
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel backgroundPerfil;
    private javax.swing.JButton btnComprarCreditos;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMudarNome;
    private javax.swing.JButton btnMudarSenha;
    private javax.swing.JLabel creditosUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaJogos;
    private javax.swing.JPanel meusjogosPanel;
    private javax.swing.JLabel nomeUser;
    private javax.swing.JPanel userInfoPanel;
    private UsuarioAbstract usuario;
    private Vector<String> jogos;
    private RepositorioUsuario repo;
    // End of variables declaration                   
}
