/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

// FALTA: 3 Exxeption Excluir e editar jogo não existente, e excluir usuario não exsistente

package system.gui;

import javax.swing.JOptionPane;

import system.gui.CriarJogo;
import system.gui.EditarJogo;
import system.gui.Login;
import system.usuario.RepositorioUsuario;
import system.jogos.Jogo;
import system.jogos.RepositorioJogos;
import system.jogos.exceptions.JIException;

/**
 *
 * @author vinic
 */
public class UsuarioADM extends javax.swing.JFrame {

  /**
   * Creates new form MenuADM
   */
  public UsuarioADM() {

    initComponents();
    this.setTitle("SpaceArcadia");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    txtJ1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    panelCreditos = new javax.swing.JPanel();
    txtCreditos = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    panelMain = new javax.swing.JPanel();
    txtOpcAdm = new javax.swing.JLabel();
    btnLogout = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jLabel8 = new javax.swing.JLabel();
    btnCriarJogo = new javax.swing.JButton();
    panelCreditos1 = new javax.swing.JPanel();
    txtCreditos1 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    panelExcluirJogo = new javax.swing.JPanel();
    jLabel5 = new javax.swing.JLabel();
    txtFExcluirJogo = new javax.swing.JTextField();
    btnEXCLUIRJogo = new javax.swing.JButton();
    btnEditarJogo = new javax.swing.JButton();
    panelExcluirUsuario = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    txtFExcluirUsuario = new javax.swing.JTextField();
    btnEXCLUIRUsuario = new javax.swing.JButton();

    jLabel1.setText("jLabel1");

    txtJ1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
    txtJ1.setForeground(new java.awt.Color(204, 0, 204));
    txtJ1.setText("Jogos");

    jLabel2.setText("jLabel2");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE));
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE));

    panelCreditos.setBackground(new java.awt.Color(102, 156, 255));
    panelCreditos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    txtCreditos.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
    txtCreditos.setForeground(new java.awt.Color(0, 0, 0));
    txtCreditos.setText("0,00");

    jLabel7.setBackground(new java.awt.Color(0, 255, 255));
    jLabel7.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(0, 0, 0));
    jLabel7.setText("Créditos:");
    jLabel7.setToolTipText("");

    javax.swing.GroupLayout panelCreditosLayout = new javax.swing.GroupLayout(panelCreditos);
    panelCreditos.setLayout(panelCreditosLayout);
    panelCreditosLayout.setHorizontalGroup(
        panelCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreditosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(46, Short.MAX_VALUE)));
    panelCreditosLayout.setVerticalGroup(
        panelCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreditosLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(txtCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);

    panelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    txtOpcAdm.setBackground(new java.awt.Color(255, 255, 255));
    txtOpcAdm.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
    txtOpcAdm.setForeground(new java.awt.Color(0, 0, 0));
    txtOpcAdm.setText("Opções de Administrador");

    btnLogout.setBackground(new java.awt.Color(102, 102, 102));
    btnLogout.setForeground(new java.awt.Color(0, 0, 0));
    btnLogout.setText("Logout");
    btnLogout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    btnLogout.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLogoutActionPerformed(evt);
      }
    });

    jPanel2.setBackground(new java.awt.Color(102, 156, 255));
    jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    jLabel8.setBackground(new java.awt.Color(0, 255, 255));
    jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(0, 0, 0));
    jLabel8.setText("Excluir ou Editar Jogo:");
    jLabel8.setToolTipText("");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap()));

    btnCriarJogo.setBackground(new java.awt.Color(102, 156, 255));
    btnCriarJogo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
    btnCriarJogo.setForeground(new java.awt.Color(0, 0, 0));
    btnCriarJogo.setText("Criar Jogo");
    btnCriarJogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    btnCriarJogo.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        btnCriarJogoStateChanged(evt);
      }
    });
    btnCriarJogo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCriarJogoActionPerformed(evt);
      }
    });

    panelCreditos1.setBackground(new java.awt.Color(102, 156, 255));
    panelCreditos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    txtCreditos1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
    txtCreditos1.setForeground(new java.awt.Color(0, 0, 0));
    txtCreditos1.setText("0,00");

    jLabel9.setBackground(new java.awt.Color(0, 255, 255));
    jLabel9.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(0, 0, 0));
    jLabel9.setText("Créditos:");
    jLabel9.setToolTipText("");

    javax.swing.GroupLayout panelCreditos1Layout = new javax.swing.GroupLayout(panelCreditos1);
    panelCreditos1.setLayout(panelCreditos1Layout);
    panelCreditos1Layout.setHorizontalGroup(
        panelCreditos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreditos1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelCreditos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCreditos1, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(49, 49, 49)));
    panelCreditos1Layout.setVerticalGroup(
        panelCreditos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreditos1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(txtCreditos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)));

    jPanel1.setBackground(new java.awt.Color(102, 156, 255));
    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    jLabel3.setBackground(new java.awt.Color(0, 255, 255));
    jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(0, 0, 0));
    jLabel3.setText("Excluir Usuário:");
    jLabel3.setToolTipText("");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE)));

    panelExcluirJogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    panelExcluirJogo.setForeground(new java.awt.Color(0, 0, 0));
    panelExcluirJogo.setPreferredSize(new java.awt.Dimension(232, 105));

    jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(0, 0, 0));
    jLabel5.setText("digite o nome do jogo:");

    txtFExcluirJogo.setBackground(new java.awt.Color(255, 255, 255));
    txtFExcluirJogo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    txtFExcluirJogo.setForeground(new java.awt.Color(0, 0, 0));
    txtFExcluirJogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    txtFExcluirJogo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtFExcluirJogoActionPerformed(evt);
      }
    });

    btnEXCLUIRJogo.setBackground(new java.awt.Color(102, 156, 255));
    btnEXCLUIRJogo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
    btnEXCLUIRJogo.setForeground(new java.awt.Color(0, 0, 0));
    btnEXCLUIRJogo.setText("EXCLUIR");

    btnEditarJogo.setBackground(new java.awt.Color(102, 156, 255));
    btnEditarJogo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
    btnEditarJogo.setForeground(new java.awt.Color(0, 0, 0));
    btnEditarJogo.setText("EDITAR");
    btnEditarJogo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEditarJogoActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelExcluirJogoLayout = new javax.swing.GroupLayout(panelExcluirJogo);
    panelExcluirJogo.setLayout(panelExcluirJogoLayout);
    panelExcluirJogoLayout.setHorizontalGroup(
        panelExcluirJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExcluirJogoLayout.createSequentialGroup()
                .addGroup(panelExcluirJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExcluirJogoLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnEditarJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEXCLUIRJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelExcluirJogoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelExcluirJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFExcluirJogo)
                            .addGroup(panelExcluirJogoLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)))))
                .addContainerGap()));
    panelExcluirJogoLayout.setVerticalGroup(
        panelExcluirJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExcluirJogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFExcluirJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelExcluirJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEXCLUIRJogo)
                    .addComponent(btnEditarJogo))
                .addGap(16, 16, 16)));

    panelExcluirUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    panelExcluirUsuario.setForeground(new java.awt.Color(0, 0, 0));
    panelExcluirUsuario.setPreferredSize(new java.awt.Dimension(214, 105));

    jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(0, 0, 0));
    jLabel6.setText("digite o nome do usuário:");

    txtFExcluirUsuario.setBackground(new java.awt.Color(255, 255, 255));
    txtFExcluirUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    txtFExcluirUsuario.setForeground(new java.awt.Color(0, 0, 0));
    txtFExcluirUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    txtFExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtFExcluirUsuarioActionPerformed(evt);
      }
    });

    btnEXCLUIRUsuario.setBackground(new java.awt.Color(102, 156, 255));
    btnEXCLUIRUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
    btnEXCLUIRUsuario.setForeground(new java.awt.Color(0, 0, 0));
    btnEXCLUIRUsuario.setText("EXCLUIR");
    btnEXCLUIRUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEXCLUIRUsuarioActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout panelExcluirUsuarioLayout = new javax.swing.GroupLayout(panelExcluirUsuario);
    panelExcluirUsuario.setLayout(panelExcluirUsuarioLayout);
    panelExcluirUsuarioLayout.setHorizontalGroup(
        panelExcluirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExcluirUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelExcluirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExcluirUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(panelExcluirUsuarioLayout.createSequentialGroup()
                        .addComponent(txtFExcluirUsuario)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExcluirUsuarioLayout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(btnEXCLUIRUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap()));
    panelExcluirUsuarioLayout.setVerticalGroup(
        panelExcluirUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExcluirUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEXCLUIRUsuario)
                .addGap(15, 15, 15)));

    javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
    panelMain.setLayout(panelMainLayout);
    panelMainLayout.setHorizontalGroup(
        panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(txtOpcAdm))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCriarJogo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelCreditos1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelExcluirJogo, javax.swing.GroupLayout.Alignment.LEADING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                            .addComponent(panelExcluirUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 339,
                                Short.MAX_VALUE))))
                .addGap(10, 10, 10)));
    panelMainLayout.setVerticalGroup(
        panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                        .addComponent(txtOpcAdm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                    .addComponent(btnCriarJogo, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(panelExcluirJogo, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(panelExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCreditos1, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>

  private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {
    this.dispose();
    new Login(new RepositorioUsuario()).setVisible(true);
  }

  private void btnCriarJogoActionPerformed(java.awt.event.ActionEvent evt) {
    CriarJogo criaJogo = new CriarJogo();
    this.dispose();
    criaJogo.show();
  }

  private void btnCriarJogoStateChanged(javax.swing.event.ChangeEvent evt) {
    // NÃO EXCREVA NADA AQUI
  }

  private void txtFExcluirJogoActionPerformed(java.awt.event.ActionEvent evt) {
    // NÃO ESCREVA NADA AQUI
  }

  private void btnEditarJogoActionPerformed(java.awt.event.ActionEvent evt) {
    
      RepositorioJogos repo = new RepositorioJogos();
      String nomeJogo = txtFExcluirJogo.getText();
      Jogo jogo = repo.procurar(nomeJogo);
      if(jogo != null){
        this.dispose();
        new EditarJogo(nomeJogo).setVisible(true);
      } else{
        JOptionPane.showMessageDialog(this, "O jogo " + nomeJogo + " não existe!");
      }
  }

  private void btnEXCLUIRJogoActionPerformed(java.awt.event.ActionEvent evt) {

    RepositorioJogos repo = new RepositorioJogos();
    String nomeJogo = txtFExcluirJogo.getText();
    Jogo jogo = repo.procurar(nomeJogo);
    if(jogo != null){
      // EXCLUIR JOGO
    } else{
      JOptionPane.showMessageDialog(this, "O jogo " + nomeJogo + " não existe!");
    }

  }

  private void txtFExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
    // NÃO ESCREVA NADA AQUI

  }

  private void btnEXCLUIRUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
    JOptionPane.showMessageDialog(this, "USUÁRIO EXCLUIDO");
    JOptionPane.showMessageDialog(this, "USUÁRIO INEXISTENTE");
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(UsuarioADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(UsuarioADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(UsuarioADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(UsuarioADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new UsuarioADM().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify
  private javax.swing.JButton btnCriarJogo;
  private javax.swing.JButton btnEXCLUIRJogo;
  private javax.swing.JButton btnEXCLUIRUsuario;
  private javax.swing.JButton btnEditarJogo;
  private javax.swing.JButton btnLogout;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel panelCreditos;
  private javax.swing.JPanel panelCreditos1;
  private javax.swing.JPanel panelExcluirJogo;
  private javax.swing.JPanel panelExcluirUsuario;
  private javax.swing.JPanel panelMain;
  private javax.swing.JLabel txtCreditos;
  private javax.swing.JLabel txtCreditos1;
  private javax.swing.JTextField txtFExcluirJogo;
  private javax.swing.JTextField txtFExcluirUsuario;
  private javax.swing.JLabel txtJ1;
  private javax.swing.JLabel txtOpcAdm;
  // End of variables declaration
}
